# Generated by Django 5.2 on 2025-05-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Attendee', 'Attendee'), ('Organizer', 'Organizer')], default='Attendee', max_length=10),
        ),
    ]
