# Generated by Django 5.2 on 2025-05-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('attendee', 'attendee'), ('organizer', 'organizer')], default='attendee', max_length=10),
        ),
    ]
